---

- name: Provision VMs
  include_tasks: vm.yaml
  when:
    vmware_vm_provisioning_limit is not defined or (
      vmware_vm_provisioning_limit is string and
      vmware_vm_provisioning_limit == vm.name
    ) or (
      vmware_vm_provisioning_limit is not string and
      vm.name in vmware_vm_provisioning_limit
    )
  with_items: "{{ vmware_vm_provisioning_vms }}"
  loop_control:
    loop_var: vm
  no_log: "{{ not vmware_vm_provisioning_force_show_log }}"
